const colors = {
    HEADER_COLOR : '#1f667e',
    STATUSBAR_COLOR: '#154555',
    SIMCARD_COLOR: '#37B4A4',
    DEVICECARD_COLOR: '#0960CA',
    JOBSCARD_COLOR: '#7AB944',
    SCHEDULECARD_COLOR: '#9381D5',
    ASSOCIATIONCARD_COLOR: '#F99500',
    CALENDARS: {
        CALENDAR_BACKGROUND_COLOR : '#FFFFFF',
        BACKGROUND_COLOR : '#00000010',
        DAY_HEADER_COLOR : '#2d4150',
        TODAY_TEXT_COLOR : 'red',
        AGENDA_KNOB_COLOR : '#1f667e',
        TEXT_SECTION_TITLE_COLOR : '#000',
        SELECTED_DAY_BACKGROUND_COLOR : '#1f667e',
        SELECTED_DAY_TEXT_COLOR : '#FFF',
        DAY_TEXT_COLOR : '#2d4150',
        MONTH_TEXT_COLOR : '#2d4150',
        TEXT_DISABLED_COLOR : '#d9e1e8',
        ARROW_COLOR : 'orange',
    }
}
export default colors;