export const USER = {
    LOGIN: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    UPDATESCHEMA_REQUEST: 'UPDATESCHEMA_REQUEST'
};

export const SIM = {
    SIM_REQUEST: 'SIM_REQUEST',
    SIM_SUCCESS: 'SIM_SUCCESS',
    SIM_FAILED: 'SIM_FAILED'
};

export const DEVICE = {
    DEVICE_REQUEST: 'DEVICE_REQUEST',
    DEVICE_SUCCESS: 'DEVICE_SUCCESS',
    DEVICE_FAILED: 'DEVICE_FAILED'
};

export const JOBS = {
    JOBS_LOGIN: 'JOBS_LOGIN',
    JOBS_SUCCESS: 'JOBS_SUCCESS',
    JOBS_FAILED: 'JOBS_FAILED'
};

export const CUSTOMER = {
    CUSTOMER_FETCH: 'CUSTOMER_FETCH',
    CUSTOMER_SUCCESS: 'CUSTOMER_SUCCESS',
    CUSTOMER_FAILED: 'CUSTOMER_FAILED'
}

export const TECHNICIAN = {
    TECHNICIAN_REQUEST: 'TECHNICIAN_REQUEST',
    TECHNICIAN_SUCCESS: 'TECHNICIAN_SUCCESS',
    TECHNICIAN_FAILED: 'TECHNICIAN_FAILED'
}

export const GPSDEVICE = {
    GPSDEVICE_REQUEST: 'GPSDEVICE_REQUEST',
    GPSDEVICE_SUCCESS: 'GPSDEVICE_SUCCESS',
    GPSDEVICE_FAILED: 'GPSDEVICE_FAILED',

    /**Device Info */
    DEVICEINFO_REQUEST: 'DEVICEINFO_REQUEST',
    DEVICEINFO_SUCCESS: 'DEVICEINFO_SUCCESS',
    DEVICEINFO_FAILED: 'DEVICEINFO_FAILED',

    /**Vehicle List */
    GPSDEVICEVEHICLELIST_REQUEST: 'GPSDEVICEVEHICLELIST_REQUEST',
    GPSDEVICEVEHICLELIST_SUCCESS: 'GPSDEVICEVEHICLELIST_SUCCESS',
    GPSDEVICEVEHICLELIST_FAILED: 'GPSDEVICEVEHICLELIST_FAILED',

    /**Check Device Association */
    CHECK_DEVICE_ASSOCIATION_REQUEST: 'CHECK_DEVICE_ASSOCIATION_REQUEST',
    CHECK_DEVICE_ASSOCIATION_SUCCESS: 'CHECK_DEVICE_ASSOCIATION_SUCCESS',
    CHECK_DEVICE_ASSOCIATION_FAILED: 'CHECK_DEVICE_ASSOCIATION_FAILED',

    /**Add GPS Device Association */
    ADD_GPS_DEVICE_REQUEST: 'ADD_GPS_DEVICE_REQUEST',
    ADD_GPS_DEVICE_SUCCESS: 'ADD_GPS_DEVICE_SUCCESS',
    ADD_GPS_DEVICE_FAILED: 'ADD_GPS_DEVICE_FAILED',

    /** On Create Vehicle Type*/
    CREATE_VEHICLETYPE_REQUEST: 'CREATEVEHICLETYPE_REQUEST',
    CREATE_VEHICLETYPE_SUCCESS: 'CREATEVEHICLETYPE_SUCCESS',
    CREATE_VEHICLETYPE_FAILED: 'CREATEVEHICLETYPE_FAILED'
}

export const ADDGPSVEHICLE = {
    ADDGPSVEHICLE_REQUEST: 'ADDGPSVEHICLE_REQUEST',
    ADDGPSVEHICLE_SUCCESS: 'ADDGPSVEHICLE_SUCCESS',
    ADDGPSVEHICLE_FAILED: 'ADDGPSVEHICLE_FAILED'
}

export const GPSDEVICETYPE = {
    GPSDEVICETYPE_REQUEST: 'GPSDEVICETYPE_REQUEST',
    GPSDEVICETYPE_SUCCESS: 'GPSDEVICETYPE_SUCCESS',
    GPSDEVICETYPE_FAILED: 'GPSDEVICETYPE_FAILED'
}

export const GPSDEVICECOUNTRYISD = {
    GPSDEVICECOUNTRYISD_REQUEST: 'GPSDEVICECOUNTRYISD_REQUEST',
    GPSDEVICECOUNTRYISD_SUCCESS: 'GPSDEVICECOUNTRYISD_SUCCESS',
    GPSDEVICECOUNTRYISD_FAILED: 'GPSDEVICECOUNTRYISD_FAILED'
}

export const GPSDEVICESEARCHCRITERIA = {
    GPSDEVICESEARCHCRITERIA_REQUEST: 'GPSDEVICESEARCHCRITERIA_REQUEST',
    GPSDEVICESEARCHCRITERIA_SUCCESS: 'GPSDEVICESEARCHCRITERIA_SUCCESS',
    GPSDEVICESEARCHCRITERIA_FAILED: 'GPSDEVICESEARCHCRITERIA_FAILED'
}